---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    # - iptables-services
    - openvpn
    - easy-rsa
    - tree
  notify: foo

- name: OpenVpn config
  copy:
    src:    server.conf
    dest:   /etc/openvpn/server.conf
    setype: openvpn_etc_t
    owner:  nobody
    group:  nobody

- name: "Generate /etc/openvpn/easy-rsa/keys dirs"
  file:
    path: "{{ item }}"
    state: directory
    mode:  0755
    owner: nobody
    group: nobody
  with_items:
    - "{{ easy_rsa_dir }}"
    - "{{ easy_rsa_dir }}/keys"

- name: Do we need to copy scripts?
  command: "test -f {{ easy_rsa_dir }}/vars"
  register: scripts_copied
  ignore_errors: true

- name: Copy scripts
  shell: "cp -rf /usr/share/easy-rsa/2.0/* {{ easy_rsa_dir }} && chown -R nobody: {{ easy_rsa_dir }}"
  when: scripts_copied | failed

- name: Remove the chance of our OpenSSL configuration not loading due to the version being undetectable
  file:
    dest: "{{ easy_rsa_dir }}/openssl.cnf"
    state: link
    src: "{{ easy_rsa_dir }}/openssl-1.0.0.cnf"

- name: Generate CA certs
  shell: "./pkitool --initca"
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/keys/ca.crt"

- name: Generate Server keys
  shell: "./pkitool --server server"
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates:  "{{ easy_rsa_dir }}/keys/server.crt"

- name: Generate Diffie-Hellman key exchange file ( this will take a while )
  shell: ./build-dh
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates:  "{{ easy_rsa_dir }}/keys/dh2048.pem"

- name: Copy keys
  shell: "cp ca.crt server.crt server.key dh2048.pem /etc/openvpn"
  args:
    chdir: "{{ easy_rsa_dir }}/keys"
    creates:  /etc/openvpn/dh2048.pem

- name: Change owner for the copied keys
  file:
    path: "/etc/openvpn/{{ item }}"
    owner: nobody
    group: nobody
  with_items:
    - dh2048.pem
    - ca.crt
    - server.crt
    - server.key

- name: Enabling ip forwarding
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    line: "net.ipv4.ip_forward = 1"

- name: Enabling OpenVPN service
  service:
    name: "openvpn@server.service"
    state: started
    enabled: yes

- include: firewalld.yml
