Vagrant.configure("2") do |config|
  config.vm.box = "centos7/base"
  config.vm.box_url = "https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box"
  config.vm.network 'forwarded_port', guest: 5099,   host: 5099

  config.vm.define :conf do |conf|
    conf.vm.network :public_network
    conf.vm.hostname = "vpnserver"
    conf.vm.synced_folder ENV['HOME'], "/home/vagrant/home"

    conf.vm.provider "virtualbox" do |v|
      v.customize ['modifyvm', :id, '--memory', '1024']
      v.customize ['modifyvm', :id, '--cpus', '1']
    end

    conf.vm.provision "ansible" do |ansible|
      ansible.playbook = "main.yml"
      ansible.inventory_path = "inv.txt"
      ansible.host_key_checking = false
    end

  end
end
